default: &default
  adapter: postgresql
  encoding: unicode

local_default: &local_default
  <<: *default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USER", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "postgres") %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>

environment_default: &environment_default
  <<: *default
  username: <%= Rails.application.credentials.databases.to_h.dig(:rachao, :username) %>
  password: <%= Rails.application.credentials.databases.to_h.dig(:rachao, :password) %>
  host: <%= Rails.application.credentials.databases.to_h.dig(:rachao, :host) %>

development:
  <<: *local_default
  database: rachao_development

test:
  <<: *local_default
  database: rachao_test

production:
  <<: *environment_default
  username: rachao
  database: <%= Rails.application.credentials.databases.to_h.dig(:rachao, :database) %>
